name: exaroton
description: Simple Exaroton API for Dart
version: 1.0.1
homepage: https://www.cidqu.net
repository: https://github.com/CidQu/exaroton

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
